lab4/urls.py
from django.contrib import admin
from django.urls import path, register_converter
from . import views, converters
from django.http import HttpResponse
import datetime


app_name = 'lab4'

register_converter(converters.NegativeIntConverter, 'negint')

urlpatterns = [
    path('', views.aboutpage),
    path('aboutpage', views.aboutpage),
    path('contact', views.contact),
    path('lab1', views.lab1),
    path('extra', views.extra),
    path('experience', views.experience),
    path('skill', views.skill),
]

lab5/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='lab5'
urlpatterns = [
    path('create', views.create_jadwal),
    path('jadwal', views.jadwal, name='jadwal'),
    path('details/<id>', views.details, name='details'),
    path('delete', views.delete)
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path, path
from django.contrib import admin
from lab_1.views import index as index_lab1


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    path('', include('lab4.urls')),
    path('', include('lab5.urls')),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),

]

lab4/models.py
from django.db import models

# Create your models here.

lab5/models.py
from django.db import models
import datetime
from django.utils import timezone

# Create your models here.
class Jadwal(models.Model):
    nama_kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=25)
    kategori = models.CharField(null=True, max_length=25)
    thnA = models.CharField(null=True, max_length=25)
    sks = models.CharField(null=True, max_length=25)
    descrip = models.CharField(null=True, max_length=100)
    tanggal = models.DateField(default=timezone.now)
    waktu = models.TimeField(default=timezone.now)

    def __str__(self):
        return self.nama_kegiatan

lab_1/models.py
from django.db import models

# Create your models here.

lab_2/models.py
from django.db import models

# Create your models here.

lab5/forms.py
from . import models
from django import forms
import datetime

class JadwalForm(forms.ModelForm):
        nama_kegiatan = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Nama Mata Kuliah",
                }))
        tempat = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Ruangan",
                }))
        kategori = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Dosen Pengajar",
                }))
        thnA = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Tahun Ajaran",
                }))
        sks = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Jumlah SKS",
                }))
        descrip = forms.CharField(widget=forms.TextInput(attrs={
                "class" : "jadwalfields full",
                "required" : True,
                "placeholder":"Deskripsi Mata Kuliah",
                }))
        tanggal = forms.DateField(widget=forms.SelectDateWidget(attrs={
                "class" : "datefield jadwalfields",
                "required" : True,
                }), initial=datetime.datetime.now() )
        waktu = forms.TimeField(widget=forms.TimeInput(attrs={
                "class" : "datefield jadwalfields",
                "placeholder":"00:00",
                "required" : True,
                }), initial=datetime.datetime.now() ) 

        class Meta:
                model = models.Jadwal
                fields = ["nama_kegiatan", "kategori", "thnA", "sks", "descrip", "tempat", "tanggal", "waktu"]

lab4/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def lab1(request):
    return render(request, "lab1.html")

def aboutpage(request):
    return render(request, "aboutpage.html")

def contact(request):
    return render(request, "contact.html")  

def extra(request):
    return render(request, "extra.html")  
    
def experience(request):
    return render(request, "experience.html")  

def skill(request):
    return render(request, "skill.html")  

lab5/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import JadwalForm
from .models import Jadwal
from django.utils import timezone
import datetime

# Create your views here.
def create_jadwal(request):
    form = JadwalForm()
    if request.method =="POST":
        form=JadwalForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lab5:jadwal')
    return render(request, "lab5/form.html", {'form':form})

def details(request, id):
    jadwal = Jadwal.objects.get(id=id)
    response = {
        'jadwal' : jadwal,
        'server_time' : datetime.datetime.now(),
    }
    return render(request, "lab5/details.html", response)

def jadwal(request):
    jadwals = Jadwal.objects.order_by("tanggal", "waktu")
    response = {
        'jadwal' : jadwals,
        'server_time' : datetime.datetime.now(),
    }
    return render(request, "lab5/jadwal.html", response)

def delete(request):
    if request.method == "POST":
        id = request.POST['id']
        Jadwal.objects.get(id=id).delete()
    return redirect('lab5:jadwal')

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Jeremiah Tennes' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2001, 2, 27) #TODO Implement this, format (Year, Month, Date)
npm = 1806204966 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab4/templates/aboutpage.html
{% include 'navbar_layout.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 30vh;">
    <div class="row">
        <div class="col-sm-4">
        <div class="img align-items-center d-flex">
        <img src="{% static 'images/userphoto.jpeg' %}" class="myImage">
        </div>
        </div>
        <div class="col-sm-8 container">
        <div>
        <div class="welcome">
            <p class="text-center">- Welcome -</p>
        <div class="home" style="margin-top: 10vh;">
            <p class="text-center">Hi there, my name is Jeremiah Garcia Tennes. I was born on 27th of February 2001. I’m currently a sophmore majoring in computer science at Universitas Indonesia.</p>
            <p class="text-center">- Feel free to check me out :) -</p>
        </div>
        </div>
        </div>
    </div>
    </div>
</div>
{% endblock %}

lab4/templates/contact.html
{% extends 'navbar_layout.html' %}
{% load static from static %}
{% block content %}
<div class="container" style="margin-top: 30vh;">
    <h1 class="welcome" style="margin-top: 15vh;">Contact me</h1>
    <div class="row">
        <div class="col-sm-4">
        <div>
		<a href="https://www.instagram.com/jeremiahtennes/">
			<img src="{% static 'images/ig.webp' %}" class="icon">
		</a>
        </div>
        </div>
        <div class="col-sm-8 container">
        <div>
        <div class="home" style="margin-top: 15vh;">
            <p class="text-center">@jeremiahtennes</p>
        </div>
        </div>
    </div>
    </div>
    
    <div class="row">
        <div class="col-sm-4">
        <div>
        <img src="{% static 'images/line.png' %}" class="icon" style="margin-top: 15vh;">
        </div>
        </div>
        <div class="col-sm-8 container">
        <div>
        <div class="home" style="margin-top: 30vh;">
            <p class="text-center">ID: jerbot04</p>
        </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}

lab4/templates/experience.html
<!DOCTYPE html>
{% extends 'navbar_layout.html' %}
{% load static from static %}
{% block content %}
<html lang="en">
		<div class="container" style="margin-top: 30vh, margin-bottom: 30vh;">
			<h1 class="welcome" style="margin-top: 15vh;">Experiences</h1>
				<div class="row">
					<div class="col-sm-4">
						<div>
							<img src="{% static 'images/tm.jpeg' %}" class="icon">
						</div>
					</div>
					<div class="col-sm-8 container">
						<div>
							<div class="home" style="margin-top: 15vh;">
								<p class="text-center">Graduated from SMAK Tirta Marta BPK Penabur at 2018.</p>
							</div>
						</div>
					</div>
				</div>
		
				<div class="row">
					<div class="col-sm-4">
						<div>
							<img src="{% static 'images/Makara_UI.png' %}" class="icon">
						</div>
					</div>
					<div class="col-sm-8 container">
						<div>
							<div class="home" style="margin-top: 20vh;">
								<p class="text-center">Enrolled in Universitas Indonesia at the year 2018 majoring in computer science.</p>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-sm-4">
						<div>
							<img src="{% static 'images/logo-bem.png' %}" class="icon">
						</div>
					</div>
					<div class="col-sm-8 container">
						<div>
							<div class="home" style="margin-top: 15vh;">
								<p class="text-center">Trainee at SBF (Sekolah Bem Fasilkom) media and design.Helped to create the 21st edition of “boolean”, which is a BEM Fasilkom magazine.</p>
							</div>
						</div>
					</div>
				</div>
		</div>
{% endblock %}

lab4/templates/extra.html
<!DOCTYPE html>
{% extends 'navbar_layout.html' %}
{% load static from static %}
{% block content %}
			<div class="container" style="margin-top: 5vh;">
				<div class="col-sm-8 container">
					<div>
						<div class="welcome">
							<p class="text-center">Ey you've made it this far</p>
							<p class="text-center">-Congrats-</p>
							<div class="home" style="margin-top: 10vh;">
								<p class="text-center">Thanks for stoppin by here's a little gif(t) for you</p>
								<p class="text-center"></p>
								<img src="{% static 'images/tenor.gif' %}" class="myImage">
							</div>
						</div>
					</div>
				</div>
			</div>

{% endblock %}

lab4/templates/lab1.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Story 1</title>
</head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
  color: black;
}
th {
  text-align: left;
  color: black;
}
h2{
color: black;
}
</style>
<body>
    <h1>Hello my name is Jeremiah Tennes</h1>
    <article>NPM : 1806204966</article>
    <article>I am 19 years old</article>
	<article>Tempat kuliah: Universitas Indonesia</article>
	<article>Angkatan: 2018</article>
	<article>Hobby: Listening to music</article>
	<article>Description: I'm just a guy being a dude, 
			 by the way below are my picture, social media profile and education background </article>
		 
	<p>My picture</p>
	<img src="{% static 'images/userphoto.jpeg' %}" alt="Profile Picture" style="width:90px;height:120px;">
	<p>Social Media</p>
	<a href="https://www.instagram.com/jeremiahtennes/">
		<img src="{% static 'images/instagram.png' %}" alt="Instagram" style="width:42px;height:42px;">
	</a>
	
	<h2>Education background</h2>
	<table style="width:100%">
	<tr>
		<th>Institution name</th>
		<th>Institution location</th> 
		<th>Year enrolled/Year graduated</th>
	</tr>
	<tr>
		<td>SD YPPK Fatima</td>
		<td>Fakfak, Papua Barat</td>
		<td>2006/2012</td>
	</tr>
	<tr>
		<td>SMP YPPK St. Don Bosco</td>
		<td>Fakfak, Papua Barat</td>
		<td>2012/2015</td>
	</tr>
	<tr>
		<td>SMAK Tirta Marta BPK Penabur</td>
		<td>Jakarta, DKI Jakarta</td>
		<td>2015/2018</td>
	</tr>
	<tr>
		<td>Universitas Indonesia</td>
		<td>Depok</td>
		<td>2018/TBA</td>
	</tr>
</table>
</body>
{% endblock %}
</html>

lab4/templates/navbar_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'style.css' %}">
    <title>PPW JT</title>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-style">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle"
                    data-toggle="collapse" data-target="#micon">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                
                <a href=""><img class="logo" src="{% static 'images/icon.webp' %}"></a>
                </div>
                <div class="collapse navbar-collapse" id="micon">
                <ul class="nav navbar-nav navbar-right">
                <li><a href="aboutpage">Home</a></li>
				<li><a href="experience">Experience</a></li>
                <li><a href="skill">Skills & portorfolio</a></li>
                <li><a href="contact">Contact me</a></li>
				<li><a href="extra">Extra</a></li>
                <li><a href="lab1">Story1</a></li>
				<li><a href="jadwal">Jadwal</a></li>
                </ul>
                </div>
        </nav>
            {% block content %}
            {% endblock %}
        </div>
</body>
    {% block script %}
    {% endblock %}
</html>

lab4/templates/skill.html
<!DOCTYPE html>
{% extends 'navbar_layout.html' %}
{% load static from static %}
{% block content %}
		<div class="container" style="margin-top: 30vh;">
			<div class="col-sm-8 container">
				<div>
					<div class="welcome">
						<p class="text-center">- Skills -</p>
						<div class="home" style="margin-top: 10vh;">
							<p class="text-center">Python</p>
							<p class="text-center">Java</p>
							<p class="text-center">HTML</p>
							<p class="text-center">CSS</p>
							<p class="text-center">Character Design</p>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="container" style="margin-top: 5vh;">
				<div class="col-sm-8 container">
					<div>
						<div class="welcome">
							<p class="text-center">-Portofolio-</p>
							<div class="home" style="margin-top: 10vh;">
								<img src="{% static 'images/lodi.JPG' %}" class="myImage">
							</div>
						</div>
					</div>
				</div>
			</div>
{% endblock %}

lab5/templates/lab5/details.html
{% extends 'navbar_layout.html' %}
{% load static %}
{% block content %}

            <div class="jadwal-card" style="color:white">
                <h2><span>{{ jadwal.kategori }}</span> - {{ jadwal.nama_kegiatan }}</h2>
                <div class="flex">
                    <div>
                        <h4>di {{ jadwal.tempat }}</h4>
                        <h5>Tahun ajaran: {{ jadwal.thnA }}</h5>
                        <h6>Jumlah sks: {{ jadwal.sks }}</h6>
                        <h7>Deskripsi: {{ jadwal.descrip }}</h7>
                        <p>{{ jadwal.tanggal }} - {{ jadwal.waktu }}</p>
                    </div>
                </div>
            </div>
        {% endblock %}

lab5/templates/lab5/form.html
{% extends 'navbar_layout.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'style5.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <title>Bikin Jadwal</title>
</head>
<body class="form-body">
    <div class="form-cont">
        <h2 style="color:white">Add Matkul</h2>
        <form method="POST" class="form">
            {% csrf_token %}
            <p>Nama Mata Kuliah</p>
            {{ form.nama_kegiatan }}
            <p>Ruangan</p>
            {{ form.tempat }}
            <p>Dosen Pengajar</p>
            {{ form.kategori }}
            <P>Tahun Ajar</P>
            {{ form.thnA }}
            <p>Jumlah SKS</p>
            {{ form.sks }}
            <p> Deskripsi Mata Kuliah </p>
            {{ form.descrip }}
            <p>Waktu & Tanggal</p>
            <p>
                {{ form.tanggal }}
                {{ form.waktu }}
            </p>
            <div class="full">
                <a href="/lab5"><button type="button" class="button delete">Back</button></a>
                <input type="submit" class="button" value="Submit" />
            </div>
        </form>
    </div>
</body>
{% endblock %}
</html>

lab5/templates/lab5/jadwal.html
{% extends 'navbar_layout.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet"  href="{% static 'style5.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
    <title>Bikin Jadwal</title>
</head>
<body>
    <div class="container">
        <h1>Jadwal Ku</h1>
        <div class="flex">
            <p>Today - {{ server_time }}</p>
            <a href="create">
                <button class="button">Create Jadwal</button>
            </a>
        </div>
            
        {% for j in jadwal %}
            <div class="jadwal-card">
                <a href="{% url 'lab5:details' id=j.pk %}">
                <h2><span>{{ j.kategori }}</span> - {{ j.nama_kegiatan }}</h2>
                </a>
                <div class="flex">
                    <div style="color:white">
                        <h4>di {{ j.tempat }}</h4>
                        <p>{{ j.tanggal }} - {{ j.waktu }}</p>
                    </div>
                    <form action="delete" method="POST" >
                        {% csrf_token %}
                        <input type="hidden" value="{{ j.id }}" name="id" />
                        <input class="button delete" type="submit" value="Delete" />
                    </form>
                </div>
            </div>
        {% endfor %}

    </div>
</body>
{% endblock %}
</html>

lab_1/templates/index_lab1.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
</head>
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 5px;
}
th {
  text-align: left;
}
</style>
<body>
    <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article>
	<article>Tempat kuliah: Universitas Indonesia</article>
	<article>Angkatan: 2018</article>
	<article>Hobby: Listening to music</article>
	<article>Description: I'm just a guy being a dude, 
			 by the way below are my picture, social media profile and education background </article>
{% load static %}			 
	<p>My picture</p>
	<img src="{% static 'images/userphoto.jpeg' %}" alt="Profile Picture" style="width:90px;height:120px;">
	<p>Social Media</p>
	<a href="https://www.instagram.com/jeremiahtennes/">
		<img src="{% static 'images/instagram.png' %}" alt="Instagram" style="width:42px;height:42px;">
	</a>
	
	<h2>Education background</h2>
	<table style="width:100%">
	<tr>
		<th>Institution name</th>
		<th>Institution location</th> 
		<th>Year enrolled/Year graduated</th>
	</tr>
	<tr>
		<td>SD YPPK Fatima</td>
		<td>Fakfak, Papua Barat</td>
		<td>2006/2012</td>
	</tr>
	<tr>
		<td>SMP YPPK St. Don Bosco</td>
		<td>Fakfak, Papua Barat</td>
		<td>2012/2015</td>
	</tr>
	<tr>
		<td>SMAK Tirta Marta BPK Penabur</td>
		<td>Jakarta, DKI Jakarta</td>
		<td>2015/2018</td>
	</tr>
	<tr>
		<td>Universitas Indonesia</td>
		<td>Depok</td>
		<td>2018/TBA</td>
	</tr>
</table>
</body>
</html>

lab_2/templates/description_lab2addon.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h3 style="text-align: center">Hi all, This is my complete biodata</h3>
    <table align="center" style="text-align: center">
        {% for bio in bio_dict %}
            <tr>
                <td class="subject">{{ bio.subject }}</td>
                <td class="value">{{ bio.value }}</td>
            </tr>
        {% endfor %}
    </table>
    <br><br>
</body>

</html>

lab_2/templates/index_lab2.html
{% extends "base.html" %}
{% block content %}
<style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is {{ name }}. {{ content }}.</p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Biodata</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<style>
    table, th, td {
        border: 1px solid black;
    }
    .subject{
        font-size: 20px;
        font-family: "Comic Sans MS";
        color: #6650ff;
    }
    .value{
        font-size: 20px;
        font-family: "Roboto", "Lucida Grande", Verdana, Arial, sans-serif;
        color: #ff102c;
    }
</style>
<body style="background-color: lightgray">
    <div class="container-fullwidth">
        <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-light">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="/lab-2/">Home</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="/lab-2-addon/">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/lab-3/">Diary</a>
              </li>
            </ul>
          </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
{% block jquery %}
{% endblock %}
</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}

templates/to_do_list.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hai semua, berikut adalah Catatan Harianku</h3>
<br><br>
<div class="row">
    <div class="col-md-6 col-xs-6">
        <table align="center" style="text-align: center">
            <tr>
                <th>Tanggal</th>
                <th>Yang akan dikerjakan</th>
            </tr>
            {% for diary_data in diary_dict %}
                <tr>
                    <td class="date">{{ diary_data.date }}</td>
                    <td class="activity">{{ diary_data.activity }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div class="col-md-6 col-xs-6">
        <form method="POST" action="add_activity/">
            {% csrf_token %}
            <table>
                <tr>
                    <td>
                        Tanggal
                    </td>
                    <td>
                        <input type="datetime-local" name="date" id="date" required="required"/>
                    </td>
                </tr>
                <tr>
                    <td>
                        Kegiatan
                    </td>
                    <td>
                        <input type="text" name="activity" id="activity" size="25"/>
                    </td>
                </tr>
            </table>
            <button type="submit" class="button btn-success">Submit</button>
        </form>
    </div>
</div>
{% endblock %}